Watermelon/src/Watermelon/ViewModels/Data/QuestionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Watermelon.Models;

namespace Watermelon.ViewModels.Data
{
    public class QuestionViewModel
    {
        [Display(Name = "Id")]
        public int QuestionId { get; set; }
        [Required(ErrorMessage = "Įveskite klausimą.")]
        [Display(Name = "Klausimas")]
        public string QuestionLine { get; set; }
        [Required(ErrorMessage = "Įveskite nuorodą.")]
        [Display(Name = "Nuoroda")]
        public string Url { get; set; }
        [Required(ErrorMessage = "Įveskite neteisingą atsakymą.")]
        [Display(Name = "Pirmas neteisingas atsakymas")]
        public string WrongAns1 { get; set; }
        [Required(ErrorMessage = "Įveskite neteisingą atsakymą.")]
        [Display(Name = "Antras neteisingas atsakymas")]
        public string WrongAns2 { get; set; }
        [Required(ErrorMessage = "Įveskite neteisingą atsakymą.")]
        [Display(Name = "Trečias neteisingas atsakymas")]
        public string WrongAns3 { get; set; }
        [Required(ErrorMessage = "Įveskite teisingą atsakymą.")]
        [Display(Name = "Teisingas atsakymas")]
        public string CorrectAns { get; set; }  // Teisingas atsakymas
        [Required(ErrorMessage = "Pasirinkite kategoriją.")]
        [Display(Name = "Kategorija")]
        public string Category { get; set; }

        public IEnumerable <Category> categories { get; set; }

        public Question GetQuestion()
        {
            Question Question = new Question();
            Question.QuestionLine = QuestionLine;
            Question.Url = Url;
            Question.WrongAns1 = WrongAns1;
            Question.WrongAns2 = WrongAns2;
            Question.WrongAns3 = WrongAns3;
            Question.CorrectAns = CorrectAns;
            Question.Category = Category;
            return Question;
        }

        public Question GetQuestionWithId()
        {
            Question Question = new Question();
            Question.QuestionId = QuestionId;
            Question.QuestionLine = QuestionLine;
            Question.Url = Url;
            Question.WrongAns1 = WrongAns1;
            Question.WrongAns2 = WrongAns2;
            Question.WrongAns3 = WrongAns3;
            Question.CorrectAns = CorrectAns;
            Question.Category = Category;
            return Question;
        }

        public void SetQuestion(Question Question)
        {
            QuestionId = Question.QuestionId;
            QuestionLine = Question.QuestionLine;
            Url = Question.Url;
            WrongAns1 = Question.WrongAns1;
            WrongAns2 = Question.WrongAns2;
            WrongAns3 = Question.WrongAns3;
            CorrectAns = Question.CorrectAns;
            Category = Question.Category;
        }
    }
}

Watermelon/src/Watermelon/Controllers/DataController.cs
using Microsoft.AspNet.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Watermelon.Models;
using Microsoft.AspNet.Http;
using Microsoft.AspNet.Authorization;
using Watermelon.ViewModels.Data;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;

namespace Watermelon.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class DataController : Controller
    {
        private GameDbContext _context;

        public DataController(GameDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {

            return View(_context.Questions.ToList());
        }

        public IActionResult CreateQuestion()
        {
            QuestionViewModel qC = new QuestionViewModel();
            qC.categories = _context.Categories.ToList();
            return View(qC);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateQuestion(QuestionViewModel Model)
        {
           if (ModelState.IsValid)
            {
                _context.Questions.Add(Model.GetQuestion());
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            Model.categories = _context.Categories.ToList();
            return View(Model);
        }

        public IActionResult EditQuestion(int id)
        {
            QuestionViewModel qC = new QuestionViewModel();
            qC.categories = _context.Categories.ToList();
            qC.SetQuestion(_context.Questions
            .Where(c => c.QuestionId == id)
            .Single());
            return View(qC);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditQuestion(QuestionViewModel Model)
        {
            if (ModelState.IsValid)
            {
                _context.Questions.Update(Model.GetQuestionWithId());
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            Model.categories = _context.Categories.ToList();
            return View(Model);
        }


        [ActionName("DeleteQuestion")]
        public IActionResult DeleteQuestion1(int id)
        {
            var question = _context.Questions
            .Where(c => c.QuestionId == id)
            .Single();

            _context.Questions.Remove(question);
            _context.SaveChanges();

            return View(question);
        }

        [HttpPost, ActionName("DeleteQuestion")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteQuestion(int id)
        {
            var question = _context.Questions
            .Where(c => c.QuestionId == id)
            .Single();

            _context.Questions.Remove(question);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult CategoriesList()
        {
            return View(_context.Categories.ToList());
        }

        public IActionResult CreateCategory()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateCategory(Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Categories.Add(category);
                _context.SaveChanges();
                return RedirectToAction("CategoriesList");
            }
            return View();
        }

        public IActionResult EditCategory(int id)
        {
            var category = _context.Categories
                .Where(c => c.CategoryId == id)
                .Single();
            return View(category);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditCategory(Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Categories.Update(category);
                _context.SaveChanges();
                return RedirectToAction("CategoriesList");
            }

            return View(category);
        }

        [ActionName("DeleteCategory")]
        public IActionResult DeleteCategory1(int id)
        {
            var category = _context.Categories
                .Where(c => c.CategoryId == id)
                .Single();

            _context.Categories.Remove(category);
            _context.SaveChanges();

            return View(category);
        }

        [HttpPost, ActionName("DeleteCategory")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteCategory(int id)
        {
            var category = _context.Categories
                .Where(c => c.CategoryId == id)
                .Single();

            _context.Categories.Remove(category);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }
       
    }
}

Watermelon/src/Watermelon/Views/Data/CategoriesList.cshtml
@model IEnumerable<Watermelon.Models.Category>

@{
    ViewBag.Title = "Kategorijų sąrašas";
}

<h2>Kategorijų sąrašas</h2>

<p align="left">
    @Html.ActionLink("Nauja kategorija", "CreateCategory")
</p>

<table class="table">
    <tr>
        <th>Id</th>
        <th>Kategorijos pav.</th>
        <th>Kategorijos eil.</th>
        <th>Kategorijos klaus.</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr align="left">
            <td>
                @Html.DisplayFor(modelItem => item.CategoryId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryLine)
            </td>
            <td>
                @Html.ActionLink("Keisti", "EditCategory", new { id = item.CategoryId })
                |
                @Html.ActionLink("Ištrinti", "DeleteCategory", new { id = item.CategoryId })
            </td>
        </tr>
    }
</table>

Watermelon/src/Watermelon/Views/Data/CreateCategory.cshtml
@model Watermelon.Models.Category

@{
    ViewBag.Title = "Sukurti kategoriją";
}

<h2>@ViewData["Title"]</h2>

<form asp-controller="Data" asp-action="CreateCategory" method="post" class="form-horizontal" role="form">
    <div class="form-horizontal">
        <div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="CategoryName" class="col-md-4 control-label"></label>
            <div class="col-md-offset-3">
                <input asp-for="CategoryName" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="CategoryLine" class="col-md-4 control-label"></label>
            <div class="col-md-offset-3">
                <input asp-for="CategoryLine" class="form-control" />
                <span asp-validation-for="CategoryLine" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-9">
                <input type="submit" value="Sukurti" class="btn btn-success" />
            </div>
        </div>
    </div>
</form>

Watermelon/src/Watermelon/Views/Data/CreateQuestion.cshtml
@model Watermelon.ViewModels.Data.QuestionViewModel

@{
    ViewBag.Title = "Sukurti klausimą";
}

<h2>@ViewData["Title"]</h2>

<form asp-controller="Data" asp-action="Create" method="post" class="form-horizontal" role="form">
    <div class="form-horizontal">
        <div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="QuestionLine" class="col-md-4 control-label"></label>
            <div class="col-md-offset-3">
                <input asp-for="QuestionLine" class="form-control" />
                <span asp-validation-for="QuestionLine" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Url" class="col-md-4 control-label"></label>
            <div class="col-md-offset-3">
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="WrongAns1" class="col-md-4 control-label"></label>
            <div class="col-md-offset-3">
                <input asp-for="WrongAns1" class="form-control" />
                <span asp-validation-for="WrongAns1" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="WrongAns2" class="col-md-4 control-label"></label>
            <div class="col-md-offset-3">
                <input asp-for="WrongAns2" class="form-control" />
                <span asp-validation-for="WrongAns2" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="WrongAns3" class="col-md-4 control-label"></label>
            <div class="col-md-offset-3">
                <input asp-for="WrongAns3" class="form-control" />
                <span asp-validation-for="WrongAns3" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="CorrectAns" class="col-md-4 control-label"></label>
            <div class="col-md-offset-3">
                <input asp-for="CorrectAns" class="form-control" />
                <span asp-validation-for="CorrectAns" class="text-danger"></span>
            </div>
        </div>
        
        <div class="form-group">
            <label asp-for="Category" class="col-md-4 control-label"></label>
            <div class="col-md-offset-3">
                <select asp-for="Category" class="col-md-9 control-label">
                    <option value="">Pasirinkite kategoriją</option>
                    @foreach (var item in Model.categories)
                    {
                        <option value="@item.CategoryName">@item.CategoryName</option>
                    }
                    
                </select>
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="form-group">
            <div class="col-md-offset-2 col-md-9">
                <input type="submit" value="Sukurti" class="btn btn-success" />
            </div>
        </div>
    </div>
</form>

Watermelon/src/Watermelon/Views/Data/DeleteCategory.cshtml
@model Watermelon.Models.Category

<h2>
    Kategorija ištrinta.
</h2>

<ul>
    <p>Id: @Model.CategoryId</p>
    <p>Pavadinimas: @Model.CategoryName</p>
    <p>Eilutė: @Model.CategoryLine</p>
    @Html.ActionLink("Atgal", "CategoriesList")

</ul>

Watermelon/src/Watermelon/Views/Data/DeleteQuestion.cshtml
@model Watermelon.Models.Question

<h2>
    Klausimas ištrintas.
</h2>

<ul>
    <p>Id: @Model.QuestionId</p>
    <p>Klausimas: @Model.QuestionLine</p>
    <p>Nuoroda: @Model.Url</p>
    @Html.ActionLink("Atgal", "Index")

</ul>

Watermelon/src/Watermelon/Views/Data/EditCategory.cshtml
@model Watermelon.Models.Category

@{
    ViewBag.Title = "Redaguoti kategoriją.";
}

<h2>@ViewData["Title"]</h2>

<form asp-controller="Data" asp-action="EditCategory" method="post" class="form-horizontal" role="form">
    <div class="form-horizontal">
        <div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>

        <div class="form-group">
            <label asp-for="CategoryId" class="col-md-4 control-label"></label>
            <div class="col-md-offset-3">
                <input asp-for="CategoryId" class="form-control" />
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="CategoryName" class="col-md-4 control-label"></label>
            <div class="col-md-offset-3">
                <input asp-for="CategoryName" class="form-control" />
                <span asp-validation-for="CategoryName" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="CategoryLine" class="col-md-4 control-label"></label>
            <div class="col-md-offset-3">
                <input asp-for="CategoryLine" class="form-control" />
                <span asp-validation-for="CategoryLine" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-9">
                <input type="submit" value="Redaguoti" class="btn btn-success" />
            </div>
        </div>
    </div>
</form>

Watermelon/src/Watermelon/Views/Data/EditQuestion.cshtml
@model Watermelon.ViewModels.Data.QuestionViewModel

@{
    ViewBag.Title = "Redaguoti klausimą.";
}

<h2>@ViewData["Title"]</h2>

<form asp-controller="Data" asp-action="Edit" method="post" class="form-horizontal" role="form">
    <div class="form-horizontal">
        <div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="QuestionId" class="col-md-4 control-label"></label>
            <div class="col-md-offset-3">
                <input asp-for="QuestionId" class="form-control" />
                <span asp-validation-for="QuestionId" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="QuestionLine" class="col-md-4 control-label"></label>
            <div class="col-md-offset-3">
                <input asp-for="QuestionLine" class="form-control" />
                <span asp-validation-for="QuestionLine" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Url" class="col-md-4 control-label"></label>
            <div class="col-md-offset-3">
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
        </div>


        <div class="form-group">
            <label asp-for="WrongAns1" class="col-md-4 control-label"></label>
            <div class="col-md-offset-3">
                <input asp-for="WrongAns1" class="form-control" />
                <span asp-validation-for="WrongAns1" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="WrongAns2" class="col-md-4 control-label"></label>
            <div class="col-md-offset-3">
                <input asp-for="WrongAns2" class="form-control" />
                <span asp-validation-for="WrongAns3" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="WrongAns3" class="col-md-4 control-label"></label>
            <div class="col-md-offset-3">
                <input asp-for="WrongAns3" class="form-control" />
                <span asp-validation-for="WrongAns3" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="CorrectAns" class="col-md-4 control-label"></label>
            <div class="col-md-offset-3">
                <input asp-for="CorrectAns" class="form-control" />
                <span asp-validation-for="CorrectAns" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="Category" class="col-md-4 control-label"></label>
            <div class="col-md-offset-3">
                <select asp-for="Category" class="col-md-9 control-label">
                    <option value="">Pasirinkite kategoriją</option>
                    @foreach (var item in Model.categories)
                    {
                        <option value="@item.CategoryName">@item.CategoryName</option>
                    }

                </select>
            </div>
        </div>
       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-9">
                <input type="submit" value="Redaguoti" class="btn btn-success" />
            </div>
        </div>
    </div>
</form>

Watermelon/src/Watermelon/Views/Data/Index.cshtml
@model IEnumerable<Watermelon.Models.Question>


@{
    ViewBag.Title = "Klausimų sąrašas";
}

<h2>Klausimų sąrašas</h2>

<p align="left">
    @Html.ActionLink("Naujas klausimas", "CreateQuestion")
    |
    @Html.ActionLink("Nauja kategorija", "CreateCategory")
    |
    @Html.ActionLink("Visos kategorijos", "CategoriesList")
</p>

<table class="table">
    <tr>
        <th>Id</th>
        <th>Klausimas</th>
        <th>Atsakymas</th>
        <th>Redaguoti</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr align="left">
            <td>
                @Html.DisplayFor(modelItem => item.QuestionId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.QuestionLine)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CorrectAns)
            </td>
            <td>
                @Html.ActionLink("Keisti", "EditQuestion", new { id = item.QuestionId })
                @Html.ActionLink("Ištrinti", "DeleteQuestion", new { id = item.QuestionId })
            </td>
        </tr>
    }
</table>